### ISSUE TITLE
Define default location

### ISSUE THREAD

**Issue by WebShapedBiz** [sanity-io/google-maps-input#64]
**Is your feature request related to a problem? Please describe.**
When adding new coordinates, the maps input always have the default position in Oslo, Norway. 

**Describe the solution you'd like**
While I understand why Oslo :-) it would be nice to have an option to set a different default location. I'm from Croatia and every time I add a location I have to scroll way down before even beginning to find my location. It's not a huge problem, but it isn't a very pleasant experience.

Cheers.

**Comment by psntr** [comment]
I was looking for that option, and it's actually already available, it's just not documented.
"GoogleMapsInputConfig" from the plugin
```
googleMapsInput(
{ 
apiKey: "YOUR_API_KEY",
defaultLocale: "en", // You can also change the map locale
defaultZoom: 13, // Adapt your zoom lvl
defaultLocation: { lat: 35.6415853080272, lng: 139.718151254117} // Change it to Croatia
}
)
```

**Comment by WebShapedBiz** [comment]
Thank you very much @psntr for your time and effort. This will help a great deal.
