### ISSUE TITLE
Sanity Studio Crash after updating styled-components to ^6

### ISSUE THREAD

**Issue by memoherrera** [sanity-io/google-maps-input#67]
**Describe the bug**

Sanity Studio started to crash after updating styled-components to ^6 version and having installed and configured properly google-maps-input.

**To Reproduce**

1. Follow instructions on to install and configure this plugin
2. Add a `geopoint` type field to any existing schema
3. Open a existing document of the schema or try to create a new document

**Expected behavior**

Yo can create or edit any document of a schema which has `geopoint` field

**Screenshots**

<img width="1335" alt="image" src="https://github.com/sanity-io/google-maps-input/assets/15003650/ecd3b945-0b58-4553-9eef-359572c47c1f">

**Which versions of Sanity are you using?**

@sanity/cli (global)              3.27.0 (latest: 3.36.3)
@sanity/cross-dataset-duplicator   1.2.0 (latest: 1.3.0)
@sanity/eslint-config-studio       3.0.0 (latest: 3.0.1)
@sanity/google-maps-input          3.0.2 (up to date)
@sanity/rich-date-input            3.0.1 (up to date)
@sanity/vision                    3.27.0 (latest: 3.36.3)
sanity                            3.27.0 (latest: 3.36.3)

**What operating system are you using?**

MacOS 14.4.1 (23E224)

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

**Additional context**

This is working good if I use  "styled-components": "^5.3.9"

**Comment by bjoerge** [comment]
Thanks for reporting! Should be fixed in v4.0.0
